Updated the script to use the '--add' flag
This fixes an issue where the entrypoint script would error
```
/entrypoint.sh: 10: [: missing ]

Error: No project active. Run with --project <projectId> or define an alias by
running firebase use --add
```